// Components
import Header from "./components/Header/page";
import Footer from "./components/Footer/page";
import Loading from "./loading";
import HeadData from "./_document";
import Head from "next/head";

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

export const metadata = {
  title: "Venexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HeadData />
      <Header />
      <body>
        {children}
        <Loading />
      </body>
      <Footer />
    </html>
  );
}
